<?php

declare(strict_types=1);

# Generated by the protocol buffer compiler (for Phluxor). DO NOT EDIT!
# source: {{ .File.Name }}
{{ $ns := .Namespace -}}
{{if $ns.Namespace}}
namespace {{ $ns.Namespace }};
{{end}}
use Phluxor\WebSocket;
{{- range $n := $ns.Import}}
use {{ $n }};
{{- end}}

class {{ .Service.Name | service }} implements {{ .Service.Name | interface }}
{
{{- range $m := .Service.Method}}
    /**
     * @param WebSocket\ContextInterface $ctx
     * @param {{ name $ns $m.InputType }} $request
     * @return {{ name $ns $m.OutputType }}
     *
     * @throws WebSocket\Exception\InvokeException
     */
    public function {{ $m.Name }}(WebSocket\ContextInterface $ctx, {{ name $ns $m.InputType }} $request): {{ name $ns $m.OutputType }} // @phpcs:ignore
    {
    	// your code
    }
{{end -}}
}
